baseURL = 'http://grustamli.com/'
languageCode = 'en-us'
title = 'Gadir Rustamli'

[params]
githubURL = "https://github.com/Grustamli"
profilePhoto = "images/profile.jpg"

[menu]
[[menu.main]]
identifier = "main"
name = "Home"
title = "Homepage"
url = "/"
