baseURL = 'http://grustamli.com/'
languageCode = 'en-us'
title = 'Gadir Rustamli'

[params]
githubURL = "https://github.com/Grustamli"
profilePhoto = "images/profile.jpg"

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
title = "Homepage"
url = "/"
weight = -110

[[menu.main]]
identifier = "articles"
name = "Articles"
title = "Articles"
url = "/articles/"
